name: Send Menu Mail

# Controls when the action will run. 
on:
  # Triggers the workflow on schedule
  schedule:
    - cron: '0 10 * * 1-5'
  
  # Triggers the workflow on push
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Send_Menu_Mail:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      
      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install feedparser

      # Runs a set of commands using the runners shell
      - name: Run Python script
        run: python ./scripts/sendmail.py
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          SEND_MENU_TO: ${{ secrets.SEND_MENU_TO }}
